# Generated by Django 2.2.1 on 2019-06-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('created', models.DateField()),
                ('image_path', models.FilePathField(max_length=120)),
                ('page_path', models.FilePathField(max_length=120)),
            ],
        ),
    ]
