# Generated by Django 2.2.1 on 2019-06-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_path',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='page_path',
            field=models.FilePathField(),
        ),
    ]
